name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'

    - name: Install dependencies
      run: npm install

    - name: Build React app
      run: npm run build

    - name: Deploy to EC2
      env:
        HOST: ${{ secrets.EC2_HOST }}
        USER: ${{ secrets.EC2_USER }}
        SSH_KEY: ${{ secrets.EC2_SSH_KEY }}
      run: |
        echo "$SSH_KEY" > M-keypair.pem
        chmod 600 M-keypair.pem
        scp -o StrictHostKeyChecking=no -i M-keypair.pem -r build/* $ubuntu@$HOST:/var/www/react-app/
        ssh -o StrictHostKeyChecking=no -i M-keypair $ubuntu@$HOST "sudo systemctl reload nginx"
