name: Deploy to EC2
on:
  push:
    branches:
      - main #branch on which your code is pushed
jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: executing remote ssh commands using password
        uses: appleboy/ssh-action@v0.1.5
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          password: ${{ secrets.EC2_PASSWORD }}
          port: ${{ secrets.PORT }}
          script: |
            # sudo yum install git
            ls  /home/ubuntu/
            sudo yum update
            sudo yum install git -y
            sudo yum install -y nodejs
            git clone https://<git access token>@https://github.com/MalikSayyed/React-app-with-cicd.git
            cd /home/ubuntu  
            # nvm use 18
            npm i
            npm i sharp
            npm run build
            nohup npm start &
